from google.cloud.bigquery import SchemaField, enums

class DefaultSchemas:
    BEHANDLINGSSTATISTIKK_MELDINGER: list[SchemaField] = [
        SchemaField("sekvensnummer", enums.SqlTypeNames.INT64),
        SchemaField("behandling_id", enums.SqlTypeNames.STRING),
        SchemaField("relatertbehandling_id", enums.SqlTypeNames.STRING),
        SchemaField("relatert_fagsystem", enums.SqlTypeNames.STRING),
        SchemaField("sak_id", enums.SqlTypeNames.STRING),
        SchemaField("aktor_id", enums.SqlTypeNames.STRING),
        SchemaField("mottatt_tid", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("registrert_tid", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("ferdigbehandlet_tid", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("utbetalt_tid", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("endret_tid", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("forventetoppstart_tid", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("teknisk_tid", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("sak_ytelse", enums.SqlTypeNames.STRING),
        SchemaField("sak_utland", enums.SqlTypeNames.STRING),
        SchemaField("behandling_type", enums.SqlTypeNames.STRING),
        SchemaField("behandling_status", enums.SqlTypeNames.STRING),
        SchemaField("behandling_resultat", enums.SqlTypeNames.STRING),
        SchemaField("behandling_metode", enums.SqlTypeNames.STRING),
        SchemaField("behandling_arsak", enums.SqlTypeNames.STRING),
        SchemaField("opprettet_av", enums.SqlTypeNames.STRING),
        SchemaField("saksbehandler", enums.SqlTypeNames.STRING),
        SchemaField("ansvarlig_beslutter", enums.SqlTypeNames.STRING),
        SchemaField("ansvarlig_enhet", enums.SqlTypeNames.STRING),
        SchemaField("tilbakekrev_belop", enums.SqlTypeNames.FLOAT64),
        SchemaField("funksjonell_periode_fom", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("funksjonell_periode_tom", enums.SqlTypeNames.TIMESTAMP),
        SchemaField("fagsystem_navn", enums.SqlTypeNames.STRING),
        SchemaField("fagsystem_versjon", enums.SqlTypeNames.STRING),
    ]
