SELECT
EXTRACT(YEAR FROM v.DATO_VEDTAK) AR,
DIM_STØNAD.DEKODE STOENAD,
DIM_RES.DEKODE RESULTAT,
--CASE 
--    WHEN COUNT(1) < 5 THEN
--        0
--    ELSE
--        COUNT(1)
--END ANTALL
COUNT(1) ANTALL

FROM PEN.t_person p
INNER JOIN PEN.T_VEDTAK v ON v.PERSON_ID = p.PERSON_ID
INNER JOIN PEN.T_KRAVHODE k ON k.KRAVHODE_ID = v.KRAVHODE_ID
INNER JOIN PEN.T_K_KRAV_GJELDER DIM_KRAV on DIM_KRAV.K_KRAV_GJELDER = k.K_KRAV_GJELDER
INNER JOIN PEN.T_K_SAK_T DIM_STØNAD ON DIM_STØNAD.K_SAK_T = v.K_SAK_T
LEFT JOIN PEN.T_SKJEMA sk on sk.kravhode_id=k.kravhode_id
INNER JOIN PEN.T_K_KLAGEANK_RES_T DIM_RES ON DIM_RES.K_KLAGEANK_RES_T = v.K_KLAGEANK_RES_T


WHERE EXTRACT (year from v.DATO_VEDTAK) >= 2021
AND v.K_VEDTAK_S = 'IVERKS'
--AND v.K_VEDTAK_S not like 'AVBR'
AND v.K_SAK_T in ('GJENLEV', 'BARNEP')
AND DIM_KRAV.K_KRAV_GJ_GRP like 'KLAGE'

GROUP BY
EXTRACT(YEAR FROM v.DATO_VEDTAK),
DIM_STØNAD.DEKODE,
DIM_RES.DEKODE

ORDER BY DIM_STØNAD.DEKODE, EXTRACT(YEAR FROM v.DATO_VEDTAK)