-- Query used in BO to create report PSAK120

SELECT
  DIM_TID_PERIODE.AAR_MAANED,
  DIM_TID_PERIODE.AAR,
  DIM_TID_PERIODE.AAR_TERTIAL_BESK_KORT,
     ( ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_ENHET_KODE_NAVN ) )

,
  ( DT_P.DIM_PENSJON_SAKTYPE.PENSJON_SAKTYPE_KODE ),
  ( DT_P.DIM_PENSJON_SAKTYPE.PENSJON_SAKTYPE_BESK ),
  ( DT_P.DIM_KRAVTYPE.KRAVTYPE_KODE ),
  ( DT_P.DIM_KRAVTYPE.KRAVTYPE_NAVN ),
  DT_P.DIM_KRAV_STATUS.KRAV_STATUS_BESK,
  DIM_BEHANDLING_TYPE_KRAV.BEHANDLING_TYPE_NAVN,
  DIM_BEHANDLING_TYPE_KRAV.BEHANDLING_TYPE_KODE,
  DT_P.DIM_OPPRETTET_AV_TYPE.OPPRETTET_AV_TYPE_KODE,
  DT_P.DIM_OPPRETTET_AV_TYPE.OPPRETTET_AV_TYPE_BESK,
  DT_P.DIM_OPPRETTET_AV_TYPE.OPPRETTET_AV_TYPE_BESK_LANG,
  sum(DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.MOTTATT_I_PERIODEN_FLAGG),
  DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FRA_SELVBETJ_LOSNING_FLAGG,
     ( ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_NIVAA1_NAVN
 ) )
,
     ( ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_NIVAA3_KODE_NAVN
 ) )
,
     ( ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_NIVAA2_NAVN
 ) )
,
  DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.LASTET_DATO,
  DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.OPPDATERT_DATO,
  DT_P.DIM_KRAV_ARSAK_TYPE.PEN_KRAV_ARSAK_TYPE_BESK,
  DT_P.DIM_KRAV_ARSAK_TYPE.PEN_KRAV_ARSAK_TYPE_KODE,
  SUM(DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.ANALYSE_KRAVHODE_ANTALL ),
  DT_P.DIM_GEOGRAFI.FYLKE_NR_NAVN,
  DT_P.DIM_GEOGRAFI.KOMMUNE_NR_NAVN,
  Case when DT_P.DIM_OPPRETTET_AV_TYPE.OPPRETTET_AV_TYPE_KODE = 'BATCH' 
then 'Opprettet av batch' 
else 'Ikke opprettet av batch'
end,
  ( Case 
When ( DT_P.DIM_KRAVTYPE.KRAVTYPE_KODE ) In ('EKSPORT','F_BH_BO_UTL','F_BH_KUN_UTL','F_BH_MED_UTL','MELLOMBH','SLUTTBEH_KUN_UTL','SLUTT_BH_UTL','UTSEND_AVTALELAND') Then 'Utland' 

When ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_ENHET_KODE
 ) In ('4475','4476','2101','4803','4862','0001') Then 'Utland' 

When ( DT_P.DIM_UTENLANDSTILSNITT.UTENLANDSTILSNITT_FIN_KODE ) In ('UTLAND','UTLAND_DVH','UTLANDSTILSNITT') then 'Utland' 


ELSE 'Nasjonal'

END ),
  ( case  DT_P.DIM_KRAVTYPE.KRAVTYPE_KODE 
when  'F_BH_BO_UTL'     then 'Førstegangsbehandling' 
when  'F_BH_KUN_UTL'   then 'Førstegangsbehandling' 
when  'F_BH_MED_UTL'  then 'Førstegangsbehandling' 
when  'FORSTEG_BH'       then 'Førstegangsbehandling' 
when  'ANKE'                    then 'Klage/anke' 
when  'KLAGE'                  then 'Klage/anke' 
when  'TILBAKEKR'           then 'Tilbakekreving' 
else  'Andre sakstyper' end )
FROM
  DT_P.DIM_TID  DIM_TID_PERIODE INNER JOIN DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV ON (DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_TID_PERIODE=DIM_TID_PERIODE.PK_DIM_TID  AND  DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_VERSJON  IN (select pk_dim_versjon from dt_p.dim_versjon where offentlig_flagg = 1))
   INNER JOIN DT_P.DIM_GEOGRAFI ON (DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_GEOGRAFI=DT_P.DIM_GEOGRAFI.PK_DIM_GEOGRAFI)
   INNER JOIN DT_P.DIM_PENSJON_SAKTYPE ON (DT_P.DIM_PENSJON_SAKTYPE.PK_DIM_PENSJON_SAKTYPE=DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_PENSJON_SAKTYPE)
   INNER JOIN DT_P.DIM_KRAV_STATUS ON (DT_P.DIM_KRAV_STATUS.PK_DIM_KRAV_STATUS=DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_KRAV_STATUS)
   INNER JOIN DT_P.DIM_KRAV_ARSAK_TYPE ON (DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_KRAV_ARSAK_TYPE=DT_P.DIM_KRAV_ARSAK_TYPE.PK_DIM_KRAV_ARSAK_TYPE)
   INNER JOIN DT_P.DIM_OPPRETTET_AV_TYPE ON (DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_OPPRETTET_AV_TYPE=DT_P.DIM_OPPRETTET_AV_TYPE.PK_DIM_OPPRETTET_AV_TYPE)
   INNER JOIN DT_P.DIM_UTENLANDSTILSNITT ON (DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_UTENLANDSTILSNITT=DT_P.DIM_UTENLANDSTILSNITT.PK_DIM_UTENLANDSTILSNITT)
   INNER JOIN DT_P.DIM_ORGANISASJON  DIM_ORGANISASJON_KRAV_PRE2017 ON (DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_ORG_KRAV_PRE2017=DIM_ORGANISASJON_KRAV_PRE2017.PK_DIM_ORGANISASJON)
   INNER JOIN DT_P.DIM_KRAVTYPE ON (DT_P.DIM_KRAVTYPE.PK_DIM_KRAVTYPE=DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_KRAVTYPE)
   INNER JOIN DT_P.DIM_BEHANDLING_TYPE  DIM_BEHANDLING_TYPE_KRAV ON (DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FK_DIM_BEHANDLING_TYPE_KRAV=DIM_BEHANDLING_TYPE_KRAV.PK_DIM_BEHANDLING_TYPE)
  
WHERE
  (
   DIM_TID_PERIODE.RELATIV_AAR  >=  -1
   AND
   DIM_TID_PERIODE.RELATIV_MAANED  <=  -1
   AND
   ( DT_P.DIM_KRAVTYPE.KRAVTYPE_KODE )  IN  ( 'F_BH_BO_UTL','F_BH_KUN_UTL','F_BH_MED_UTL','FORSTEG_BH','INNT_E'  )
  )
GROUP BY
  DIM_TID_PERIODE.AAR_MAANED, 
  DIM_TID_PERIODE.AAR, 
  DIM_TID_PERIODE.AAR_TERTIAL_BESK_KORT, 
     ( ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_ENHET_KODE_NAVN ) )

, 
  ( DT_P.DIM_PENSJON_SAKTYPE.PENSJON_SAKTYPE_KODE ), 
  ( DT_P.DIM_PENSJON_SAKTYPE.PENSJON_SAKTYPE_BESK ), 
  ( DT_P.DIM_KRAVTYPE.KRAVTYPE_KODE ), 
  ( DT_P.DIM_KRAVTYPE.KRAVTYPE_NAVN ), 
  DT_P.DIM_KRAV_STATUS.KRAV_STATUS_BESK, 
  DIM_BEHANDLING_TYPE_KRAV.BEHANDLING_TYPE_NAVN, 
  DIM_BEHANDLING_TYPE_KRAV.BEHANDLING_TYPE_KODE, 
  DT_P.DIM_OPPRETTET_AV_TYPE.OPPRETTET_AV_TYPE_KODE, 
  DT_P.DIM_OPPRETTET_AV_TYPE.OPPRETTET_AV_TYPE_BESK, 
  DT_P.DIM_OPPRETTET_AV_TYPE.OPPRETTET_AV_TYPE_BESK_LANG, 
  DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.FRA_SELVBETJ_LOSNING_FLAGG, 
     ( ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_NIVAA1_NAVN
 ) )
, 
     ( ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_NIVAA3_KODE_NAVN
 ) )
, 
     ( ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_NIVAA2_NAVN
 ) )
, 
  DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.LASTET_DATO, 
  DT_P.FAK_RAP_KRAVH_FERDIGBH_NAV.OPPDATERT_DATO, 
  DT_P.DIM_KRAV_ARSAK_TYPE.PEN_KRAV_ARSAK_TYPE_BESK, 
  DT_P.DIM_KRAV_ARSAK_TYPE.PEN_KRAV_ARSAK_TYPE_KODE, 
  DT_P.DIM_GEOGRAFI.FYLKE_NR_NAVN, 
  DT_P.DIM_GEOGRAFI.KOMMUNE_NR_NAVN, 
  Case when DT_P.DIM_OPPRETTET_AV_TYPE.OPPRETTET_AV_TYPE_KODE = 'BATCH' 
then 'Opprettet av batch' 
else 'Ikke opprettet av batch'
end, 
  ( Case 
When ( DT_P.DIM_KRAVTYPE.KRAVTYPE_KODE ) In ('EKSPORT','F_BH_BO_UTL','F_BH_KUN_UTL','F_BH_MED_UTL','MELLOMBH','SLUTTBEH_KUN_UTL','SLUTT_BH_UTL','UTSEND_AVTALELAND') Then 'Utland' 

When ( DIM_ORGANISASJON_KRAV_PRE2017.NAV_ENHET_KODE
 ) In ('4475','4476','2101','4803','4862','0001') Then 'Utland' 

When ( DT_P.DIM_UTENLANDSTILSNITT.UTENLANDSTILSNITT_FIN_KODE ) In ('UTLAND','UTLAND_DVH','UTLANDSTILSNITT') then 'Utland' 


ELSE 'Nasjonal'

END ), 
  ( case  DT_P.DIM_KRAVTYPE.KRAVTYPE_KODE 
when  'F_BH_BO_UTL'     then 'Førstegangsbehandling' 
when  'F_BH_KUN_UTL'   then 'Førstegangsbehandling' 
when  'F_BH_MED_UTL'  then 'Førstegangsbehandling' 
when  'FORSTEG_BH'       then 'Førstegangsbehandling' 
when  'ANKE'                    then 'Klage/anke' 
when  'KLAGE'                  then 'Klage/anke' 
when  'TILBAKEKR'           then 'Tilbakekreving' 
else  'Andre sakstyper' end )
