select opp.BEHANDLINGSMANED, beh.HOVEDYTELSE, beh.DELYTELSE, beh.OPPG_BESKR_KODER, count(beh.OPPG_BESKR_KODER) from PEN.T_ALDERSOVERGANG_OPPSUMMERING opp
    join PEN.T_ALDERSOVERGANG_OPPSUMMERING_BEHANDLING beh on opp.ID = beh.ALDERSOVERGANG_OPPSUMMERING_ID
where beh.OPPG_BESKR_KODER is not null group by opp.BEHANDLINGSMANED, beh.HOVEDYTELSE, beh.DELYTELSE, beh.OPPG_BESKR_KODER