select opp.BEHANDLINGSMANED, brev.KATEGORI_KODE, brev.BREV_KODE, count(BREV_KODE)
from PEN.T_ALDERSOVERGANG_OPPSUMMERING opp join PEN.T_ALDERSOVERGANG_OPPSUMMERING_BREV brev on opp.ID = brev.ALDERSOVERGANG_OPPSUMMERING_ID
group by opp.BEHANDLINGSMANED, brev.KATEGORI_KODE, brev.BREV_KODE