--MÅNEDSDATA
--Førstegangskrav totalt minus krav som er opprettet i forbindelse med alderskonvertering
SELECT
EXTRACT(YEAR FROM k.DATO_OPPRETTET) ÅR, 
EXTRACT(MONTH FROM k.DATO_OPPRETTET) MÅNED,
COUNT(1) antall

FROM PEN.t_person p
INNER JOIN PEN.t_sak s ON s.person_id = p.PERSON_ID
INNER JOIN PEN.T_KRAVHODE k ON k.SAK_ID = s.SAK_ID

WHERE s.K_SAK_T = 'ALDER'
AND k.K_KRAV_GJELDER IN ('F_BH_BO_UTL','F_BH_MED_UTL','FORSTEG_BH','F_BH_KUN_UTL')
--and EXTRACT (year from k.DATO_OPPRETTET) = 2021
--and k.K_KRAV_S not like 'AVBRUTT'
AND k.OPPRETTET_AV NOT LIKE 'BPEN006'

GROUP BY 
EXTRACT(YEAR FROM k.DATO_OPPRETTET),
EXTRACT(MONTH FROM k.DATO_OPPRETTET)

ORDER BY EXTRACT(YEAR FROM k.DATO_OPPRETTET),
EXTRACT(MONTH FROM k.DATO_OPPRETTET) ASC