SELECT TO_CHAR(k.DATO_MOTTATT_KRAV, 'yyyy') AR,
  TO_CHAR(k.DATO_MOTTATT_KRAV, 'mm') MANED,
  TO_CHAR(k.DATO_MOTTATT_KRAV, 'yyyy-mm') "AR_MANED",
  DS.DEKODE STONAD,
  DK.DEKODE KRAVTYPE,
  CASE
    WHEN COUNT(1) < 5
    THEN 0
    ELSE COUNT(1)
  END ANTALL
FROM PEN.T_PERSON P
INNER JOIN PEN.T_SAK S
ON P.PERSON_ID = S.PERSON_ID
INNER JOIN PEN.T_KRAVHODE K
ON S.SAK_ID = K.SAK_ID
INNER JOIN PEN.T_K_SAK_T DS
ON S.K_SAK_T                               = DS.K_SAK_T
INNER JOIN PEN.T_K_KRAV_GJELDER DK
ON K.K_KRAV_GJELDER                           = DK.K_KRAV_GJELDER
WHERE EXTRACT(YEAR FROM K.DATO_MOTTATT_KRAV) >= 2021
AND K.K_KRAV_GJELDER                         IN ('F_BH_BO_UTL', 'F_BH_KUN_UTL', 'F_BH_MED_UTL', 'FORSTEG_BH')
GROUP BY TO_CHAR(k.DATO_MOTTATT_KRAV, 'yyyy'),
  TO_CHAR(k.DATO_MOTTATT_KRAV, 'mm'),
  TO_CHAR(k.DATO_MOTTATT_KRAV, 'yyyy-mm'),
  DS.DEKODE,
  DK.DEKODE
  