SELECT DK.DEKODE,
  EXTRACT( YEAR FROM K.DATO_MOTTATT_KRAV) AR,
  EXTRACT( MONTH FROM K.DATO_MOTTATT_KRAV) MANED,
  EXTRACT(YEAR FROM v.DATO_VEDTAK) || '-' || EXTRACT(MONTH FROM v.DATO_VEDTAK) "AR_MANED",
  CASE
    WHEN COUNT(1) < 5
    THEN 0
    ELSE COUNT(1)
  END ANTALL
FROM PEN.T_PERSON P
INNER JOIN PEN.T_SAK S
ON P.PERSON_ID = S.PERSON_ID
INNER JOIN PEN.T_KRAVHODE K
ON S.SAK_ID = K.SAK_ID
INNER JOIN PEN.T_K_KRAV_GJELDER DK
ON K.K_KRAV_GJELDER                           = DK.K_KRAV_GJELDER
WHERE EXTRACT(YEAR FROM K.DATO_MOTTATT_KRAV) >= 2021
AND S.K_SAK_T                                IN ('BARNEP', 'GJENLEV')
AND K.K_KRAV_GJELDER                         IN ('F_BH_BO_UTL', 'F_BH_KUN_UTL', 'F_BH_MED_UTL', 'FORSTEG_BH')
  --and k.k_initiert_av like 'BRUKER' --usikker på denne
  --and k.k_krav_gjelder not like 'REVURD'
GROUP BY EXTRACT( YEAR FROM K.DATO_MOTTATT_KRAV),
  EXTRACT( MONTH FROM K.DATO_MOTTATT_KRAV),
  EXTRACT(YEAR FROM v.DATO_VEDTAK) || '-' || EXTRACT(MONTH FROM v.DATO_VEDTAK)
  DK.DEKODE;