SELECT
TO_CHAR(v.DATO_VEDTAK, 'yyyy') AR,
TO_CHAR(v.DATO_VEDTAK, 'mm') MANED,
TO_CHAR(v.DATO_VEDTAK, 'yyyy-mm') "AR_MANED",
DIM_STØNAD.DEKODE STOENAD,
CASE
    WHEN v.K_VEDTAK_T = 'REGULERING' THEN
        'Regulering'
    ELSE DIM_KRAV.DEKODE 
END KRAVTYPE,
EXTRACT(day from v.DATO_VEDTAK - k.DATO_OPPRETTET) DAGER

FROM PEN.t_person p
INNER JOIN PEN.T_VEDTAK v ON v.PERSON_ID = p.PERSON_ID
INNER JOIN PEN.T_KRAVHODE k ON k.KRAVHODE_ID = v.KRAVHODE_ID
LEFT JOIN PEN.T_K_KRAV_GJELDER DIM_KRAV on DIM_KRAV.K_KRAV_GJELDER = k.K_KRAV_GJELDER
LEFT JOIN PEN.T_K_SAK_T DIM_STØNAD ON DIM_STØNAD.K_SAK_T = v.K_SAK_T

WHERE EXTRACT (year from v.DATO_VEDTAK) >= 2021
AND v.K_VEDTAK_S = 'IVERKS'
AND v.K_VEDTAK_T not like 'REGULERING'
