SELECT
EXTRACT(YEAR FROM v.DATO_VEDTAK) AR, 
--EXTRACT(MONTH FROM v.DATO_VEDTAK) MANED,
--EXTRACT(YEAR FROM v.DATO_VEDTAK) || '-' || EXTRACT(MONTH FROM v.DATO_VEDTAK) "AR_MANED",
DIM_STØNAD.DEKODE STOENAD,
CASE
    WHEN v.K_VEDTAK_T = 'REGULERING' THEN
        'Regulering'
    ELSE DIM_KRAV.DEKODE 
END KRAVTYPE,
AVG(EXTRACT( day from v.DATO_VEDTAK - k.DATO_OPPRETTET)) gj_dager, -- Kanskje bedre med k.DATO_MOTTATT_KRAV, men det blir krøll med extract
MEDIAN(EXTRACT( day from v.DATO_VEDTAK - k.DATO_OPPRETTET)) med_dager,
count(*) antall

FROM PEN.t_person p
INNER JOIN PEN.T_VEDTAK v ON v.PERSON_ID = p.PERSON_ID
INNER JOIN PEN.T_KRAVHODE k ON k.KRAVHODE_ID = v.KRAVHODE_ID
INNER JOIN PEN.T_KRAV_ARSAK ka ON ka.KRAVHODE_ID = v.KRAVHODE_ID
INNER JOIN PEN.T_K_KRAV_GJELDER DIM_KRAV on DIM_KRAV.K_KRAV_GJELDER = k.K_KRAV_GJELDER
INNER JOIN PEN.T_K_SAK_T DIM_STØNAD ON DIM_STØNAD.K_SAK_T = v.K_SAK_T
LEFT JOIN PEN.T_SKJEMA sk on sk.kravhode_id=k.kravhode_id

WHERE EXTRACT (year from v.DATO_VEDTAK) >= 2021
AND v.K_VEDTAK_S = 'IVERKS'
AND v.K_SAK_T in ('GJENLEV', 'BARNEP')
AND v.K_VEDTAK_T not like 'REGULERING'

GROUP BY
EXTRACT(YEAR FROM v.DATO_VEDTAK), 
--EXTRACT(MONTH FROM v.DATO_VEDTAK),
--EXTRACT(YEAR FROM v.DATO_VEDTAK) || '-' || EXTRACT(MONTH FROM v.DATO_VEDTAK),
DIM_STØNAD.DEKODE,
CASE
    WHEN v.K_VEDTAK_T = 'REGULERING' THEN
        'Regulering'
    ELSE DIM_KRAV.DEKODE 
END

ORDER BY DIM_STØNAD.DEKODE
