SELECT TRUNC(sysdate) - 1      AS DATO,
       b.BEHANDLING_CODE       AS BEHANDLINGSTYPE,
       bm.UNDERKATEGORI_KODE   AS UNDERKATEGORI,
       bm.OPPGAVE_KODE         AS OPPGAVEKODE,
       bm.FAGOMRADE,
       MIN(bm.KATEGORI_DECODE) KEEP (DENSE_RANK LAST ORDER BY bm.OPPRETTET) AS KATEGORI,
       COUNT(*)                AS ANTALL
FROM PEN.T_BEHANDLING b
         JOIN PEN.T_AKTIVITET a
              ON b.BEHANDLING_ID = a.BEHANDLING_ID
         JOIN PEN.T_BEHANDLING_MANUELL bm
              ON a.AKTIVITET_ID = bm.AKTIVITET_ID
WHERE TRUNC(bm.OPPRETTET) = TRUNC(sysdate) - 1
group by b.BEHANDLING_CODE, bm.UNDERKATEGORI_KODE, bm.OPPGAVE_KODE, bm.FAGOMRADE, bm.KATEGORI
ORDER BY ANTALL DESC;