SELECT
EXTRACT(YEAR FROM k.DATO_OPPRETTET) ÅR, 
EXTRACT(MONTH FROM k.DATO_OPPRETTET) MÅNED,
EXTRACT(YEAR FROM k.DATO_OPPRETTET) || '-' || EXTRACT(MONTH FROM k.DATO_OPPRETTET) "ÅR-MÅNED",
DIM_STØNAD.DEKODE STØNADSOMRÅDE,
DIM_KRAV.DEKODE KRAVTYPE,
CASE
    WHEN sk.OPPRETTET_AV IS NULL THEN
        'saksbehandler'  
    WHEN sk.OPPRETTET_AV BETWEEN '00000000000' AND '99999999999' THEN
        'bruker'
    WHEN sk.OPPRETTET_AV NOT BETWEEN '00000000000' AND '99999999999' THEN
        'saksbehandler'
END OPPRETTET_AV,
CASE
    WHEN k.k_behandling_t = 'DEL_AUTO' THEN
        'MAN'
    ELSE k.k_behandling_t
END AUTOMATISERING,
CASE 
    WHEN SUBSTR(k.OPPRETTET_AV,2,3) like 'PEN'
    OR k.OPPRETTET_AV like 'KONVERTERING'
    THEN 'opprettet av batch'
    ELSE 'ikke opprettet av batch'
END BATCH_FLAGG,
COALESCE(COUNT(1), 0) ANTALL

FROM PEN.t_person p
INNER JOIN PEN.t_sak s ON s.person_id = p.PERSON_ID
INNER JOIN PEN.T_K_SAK_T DIM_STØNAD ON DIM_STØNAD.K_SAK_T = s.K_SAK_T
INNER JOIN PEN.T_KRAVHODE k ON k.SAK_ID = s.SAK_ID
INNER JOIN PEN.T_K_KRAV_GJELDER DIM_KRAV on DIM_KRAV.K_KRAV_GJELDER = k.K_KRAV_GJELDER
LEFT JOIN PEN.T_SKJEMA sk on sk.kravhode_id=k.kravhode_id


--WHERE s.K_SAK_T = 'ALDER'
--WHERE k.K_KRAV_GJELDER IN ('F_BH_BO_UTL','F_BH_MED_UTL','FORSTEG_BH','F_BH_KUN_UTL')
--WHERE k.K_KRAV_GJELDER NOT LIKE ('REGULERING')
WHERE EXTRACT (year from k.DATO_OPPRETTET) >= 2021
--and k.K_KRAV_S not like 'AVBRUTT'
--AND k.K_KRAV_GJELDER NOT LIKE ('REGULERING')

----- BPEN006 eneste batch siden 2012. For å se på eldre må vi fjerne andre batcher og konvertering i tillegg: -----
--AND SUBSTR(k.OPPRETTET_AV,2,3) not like 'PEN'
--AND k.OPPRETTET_AV not like 'KONVERTERING'

GROUP BY 
EXTRACT(YEAR FROM k.DATO_OPPRETTET),
EXTRACT(MONTH FROM k.DATO_OPPRETTET),
EXTRACT(YEAR FROM k.DATO_OPPRETTET) || '-' || EXTRACT(MONTH FROM k.DATO_OPPRETTET),
DIM_STØNAD.DEKODE,
DIM_KRAV.DEKODE,
CASE
    WHEN sk.OPPRETTET_AV IS NULL THEN
        'saksbehandler'    
    WHEN sk.OPPRETTET_AV BETWEEN '00000000000' AND '99999999999' THEN
        'bruker'
    WHEN sk.OPPRETTET_AV NOT BETWEEN '00000000000' AND '99999999999' THEN
        'saksbehandler'
END,
CASE
    WHEN k.k_behandling_t = 'DEL_AUTO' THEN
        'MAN'
    ELSE k.k_behandling_t
END,
CASE 
    WHEN SUBSTR(k.OPPRETTET_AV,2,3) like 'PEN'
    OR k.OPPRETTET_AV like 'KONVERTERING'
    THEN 'opprettet av batch'
    ELSE 'ikke opprettet av batch'
END
--ORDER BY EXTRACT(YEAR FROM k.DATO_OPPRETTET),
--EXTRACT(MONTH FROM k.DATO_OPPRETTET) ASC
ORDER BY ANTALL DESC