SELECT
EXTRACT(YEAR FROM v.DATO_VEDTAK) ÅR, 
EXTRACT(MONTH FROM v.DATO_VEDTAK) MÅNED,
EXTRACT(YEAR FROM v.DATO_VEDTAK) || '-' || EXTRACT(MONTH FROM v.DATO_VEDTAK) "ÅR-MÅNED",
DIM_STØNAD.DEKODE STØNADSOMRÅDE,
DIM_KRAV.DEKODE KRAVTYPE,
CASE
    WHEN v.ANSV_SAKSBH BETWEEN '00000000000' AND '99999999999' THEN
        'bruker'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,1) between 'A' and 'Z' AND SUBSTR(v.ANSV_SAKSBH,2,1) between '0' and '9' THEN
        'saksbehandler'
    ELSE v.ANSV_SAKSBH
    END ANSV_SAKSBH,
CASE
    WHEN SUBSTR(k.OPPRETTET_AV,2,3) like 'PEN'
        OR k.OPPRETTET_AV like 'KONVERTERING' THEN
        k.OPPRETTET_AV     
    WHEN sk.OPPRETTET_AV IS NULL or k.kravkilde is not null THEN
        'saksbehandler'
    WHEN k.OPPRETTET_AV BETWEEN '00000000000' AND '99999999999' THEN
        'bruker'
    WHEN k.OPPRETTET_AV NOT BETWEEN '00000000000' AND '99999999999' THEN
        'saksbehandler'
END K_OPPRETTET_AV,
CASE
    WHEN SUBSTR(v.OPPRETTET_AV,2,3) like 'PEN'
        OR v.OPPRETTET_AV like 'KONVERTERING' THEN
        v.OPPRETTET_AV
    WHEN v.OPPRETTET_AV BETWEEN '00000000000' AND '99999999999' THEN
        'bruker'
    WHEN v.OPPRETTET_AV NOT BETWEEN '00000000000' AND '99999999999' THEN
        'saksbehandler'
END V_OPPRETTET_AV,
k.k_behandling_t KRAV_AUTO,
v.k_behandling_t VEDTAK_AUTO,
CASE 
    WHEN SUBSTR(k.OPPRETTET_AV,1,4) like 'BPEN'
    OR k.OPPRETTET_AV like 'KONVERTERING'
    THEN 1
    ELSE 0
END BATCH_FLAGG,
COUNT(1) ANTALL

FROM PEN.t_person p
INNER JOIN PEN.T_VEDTAK v ON v.PERSON_ID = p.PERSON_ID
INNER JOIN PEN.T_KRAVHODE k ON k.KRAVHODE_ID = v.KRAVHODE_ID
INNER JOIN PEN.T_K_KRAV_GJELDER DIM_KRAV on DIM_KRAV.K_KRAV_GJELDER = k.K_KRAV_GJELDER
INNER JOIN PEN.T_K_SAK_T DIM_STØNAD ON DIM_STØNAD.K_SAK_T = v.K_SAK_T
LEFT JOIN PEN.T_SKJEMA sk on sk.kravhode_id=k.kravhode_id


--WHERE s.K_SAK_T = 'ALDER'
--WHERE k.K_KRAV_GJELDER IN ('F_BH_BO_UTL','F_BH_MED_UTL','FORSTEG_BH','F_BH_KUN_UTL')
--WHERE k.K_KRAV_GJELDER NOT LIKE ('REGULERING')
WHERE EXTRACT (year from v.DATO_VEDTAK) >= 2021
AND v.K_VEDTAK_S = 'IVERKS'
--and k.K_KRAV_S not like 'AVBRUTT'
--AND k.K_KRAV_GJELDER NOT LIKE ('REGULERING')

----- BPEN006 eneste batch siden 2012. For å se på eldre må vi fjerne andre batcher og konvertering i tillegg: -----
--AND SUBSTR(k.OPPRETTET_AV,2,3) not like 'PEN'
--AND k.OPPRETTET_AV not like 'KONVERTERING'

GROUP BY 
EXTRACT(YEAR FROM v.DATO_VEDTAK), 
EXTRACT(MONTH FROM v.DATO_VEDTAK),
EXTRACT(YEAR FROM v.DATO_VEDTAK) || '-' || EXTRACT(MONTH FROM v.DATO_VEDTAK),
DIM_STØNAD.DEKODE,
DIM_KRAV.DEKODE,
CASE
    WHEN v.ANSV_SAKSBH BETWEEN '00000000000' AND '99999999999' THEN
        'bruker'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,1) between 'A' and 'Z' AND SUBSTR(v.ANSV_SAKSBH,2,1) between '0' and '9' THEN
        'saksbehandler'
    ELSE v.ANSV_SAKSBH
    END,
CASE
    WHEN SUBSTR(k.OPPRETTET_AV,2,3) like 'PEN'
        OR k.OPPRETTET_AV like 'KONVERTERING' THEN
        k.OPPRETTET_AV     
    WHEN sk.OPPRETTET_AV IS NULL or k.kravkilde is not null THEN
        'saksbehandler'
    WHEN k.OPPRETTET_AV BETWEEN '00000000000' AND '99999999999' THEN
        'bruker'
    WHEN k.OPPRETTET_AV NOT BETWEEN '00000000000' AND '99999999999' THEN
        'saksbehandler'
END,
CASE
    WHEN SUBSTR(v.OPPRETTET_AV,2,3) like 'PEN'
        OR v.OPPRETTET_AV like 'KONVERTERING' THEN
        v.OPPRETTET_AV    
    WHEN v.OPPRETTET_AV BETWEEN '00000000000' AND '99999999999' THEN
        'bruker'
    WHEN v.OPPRETTET_AV NOT BETWEEN '00000000000' AND '99999999999' THEN
        'saksbehandler'
END,
k.k_behandling_t,
v.k_behandling_t,
CASE 
    WHEN SUBSTR(k.OPPRETTET_AV,1,4) like 'BPEN'
    OR k.OPPRETTET_AV like 'KONVERTERING'
    THEN 1
    ELSE 0
END 
ORDER BY EXTRACT(YEAR FROM v.DATO_VEDTAK),
EXTRACT(MONTH FROM v.DATO_VEDTAK) ASC
--ORDER BY ANTALL DESC