SELECT
EXTRACT(YEAR FROM v.DATO_VEDTAK) AAR, 
EXTRACT(MONTH FROM v.DATO_VEDTAK) MAANED,
EXTRACT(YEAR FROM v.DATO_VEDTAK) || '-' || EXTRACT(MONTH FROM v.DATO_VEDTAK) "AAR_MAANED",
DIM_STØNAD.DEKODE STOENAD,
CASE
    WHEN v.K_VEDTAK_T = 'REGULERING' THEN
        'Regulering'
    ELSE DIM_KRAV.DEKODE 
END KRAVTYPE,
CASE
    WHEN v.ANSV_SAKSBH BETWEEN '00000000000' AND '99999999999' THEN
        'Bruker'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,1) between 'A' and 'Z' AND SUBSTR(v.ANSV_SAKSBH,2,1) between '0' and '9' THEN
        'Saksbehandler'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,4) like 'BPEN' THEN
        'Batch'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,4) like 'PPEN' OR SUBSTR(v.ANSV_SAKSBH,1,4) like 'AUTO' OR v.ANSV_SAKSBH like 'PP01' THEN
        'Prosess'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,4) like 'TPEN' THEN
        'Tjeneste'
    WHEN v.ANSV_SAKSBH in ('KONV', 'srvWAS', 'srvtps', 'srvPersonkort', 'srvpinst', 'srvpselv', 'Temporary', 'UNKNOWN_USER') THEN
        'Provider tjeneste'
    ELSE 'Annet'
END ANSV_SAKSBH,
CASE 
    WHEN v.K_VEDTAK_T = 'REGULERING' THEN
        'AUTO'
    ELSE k.k_behandling_t 
    END KRAV_BEHANDLING,
CASE 
    WHEN COUNT(1) < 5 THEN
        0
    ELSE
        COUNT(1)
END ANTALL

FROM PEN.t_person p
INNER JOIN PEN.T_VEDTAK v ON v.PERSON_ID = p.PERSON_ID
INNER JOIN PEN.T_KRAVHODE k ON k.KRAVHODE_ID = v.KRAVHODE_ID
INNER JOIN PEN.T_K_KRAV_GJELDER DIM_KRAV on DIM_KRAV.K_KRAV_GJELDER = k.K_KRAV_GJELDER
INNER JOIN PEN.T_K_SAK_T DIM_STØNAD ON DIM_STØNAD.K_SAK_T = v.K_SAK_T
LEFT JOIN PEN.T_SKJEMA sk on sk.kravhode_id=k.kravhode_id


--WHERE EXTRACT (year from v.DATO_VEDTAK) >= 2021
WHERE v.K_VEDTAK_S = 'IVERKS'
AND v.DATO_VEDTAK IS NOT NULL --Bare to rader med status iverksatt uten dato_vedtak

GROUP BY
EXTRACT(YEAR FROM v.DATO_VEDTAK), 
EXTRACT(MONTH FROM v.DATO_VEDTAK),
EXTRACT(YEAR FROM v.DATO_VEDTAK) || '-' || EXTRACT(MONTH FROM v.DATO_VEDTAK),
DIM_STØNAD.DEKODE,
CASE
    WHEN v.K_VEDTAK_T = 'REGULERING' THEN
        'Regulering'
    ELSE DIM_KRAV.DEKODE 
END,
CASE
    WHEN v.ANSV_SAKSBH BETWEEN '00000000000' AND '99999999999' THEN
        'Bruker'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,1) between 'A' and 'Z' AND SUBSTR(v.ANSV_SAKSBH,2,1) between '0' and '9' THEN
        'Saksbehandler'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,4) like 'BPEN' THEN
        'Batch'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,4) like 'PPEN' OR SUBSTR(v.ANSV_SAKSBH,1,4) like 'AUTO' OR v.ANSV_SAKSBH like 'PP01' THEN
        'Prosess'
    WHEN SUBSTR(v.ANSV_SAKSBH,1,4) like 'TPEN' THEN
        'Tjeneste'
    WHEN v.ANSV_SAKSBH in ('KONV', 'srvWAS', 'srvtps', 'srvPersonkort', 'srvpinst', 'srvpselv', 'Temporary', 'UNKNOWN_USER') THEN
        'Provider tjeneste'
    ELSE 'Annet'
END,
CASE 
    WHEN v.K_VEDTAK_T = 'REGULERING' THEN
        'AUTO'
    ELSE k.k_behandling_t 
END

ORDER BY EXTRACT(YEAR FROM v.DATO_VEDTAK) ASC,
EXTRACT(MONTH FROM v.DATO_VEDTAK) ASC